// <auto-generated />
using AppsInventory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AppsInventory.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211005035342_InitialDatabaseMigration")]
    partial class InitialDatabaseMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AppsInventory.Data.Models.ConfigItem", b =>
                {
                    b.Property<int>("ConfigItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ConfigListId")
                        .HasColumnType("int");

                    b.Property<string>("ItemDescripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegBorrado")
                        .HasColumnType("int");

                    b.HasKey("ConfigItemId");

                    b.HasIndex("ConfigListId");

                    b.ToTable("ConfigItem");
                });

            modelBuilder.Entity("AppsInventory.Data.Models.ConfigList", b =>
                {
                    b.Property<int>("ConfigListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ListDescripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegBorrado")
                        .HasColumnType("int");

                    b.HasKey("ConfigListId");

                    b.ToTable("ConfigLists");
                });

            modelBuilder.Entity("AppsInventory.Data.Models.ConfigItem", b =>
                {
                    b.HasOne("AppsInventory.Data.Models.ConfigList", "ConfigList")
                        .WithMany("ConfigItem")
                        .HasForeignKey("ConfigListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfigList");
                });

            modelBuilder.Entity("AppsInventory.Data.Models.ConfigList", b =>
                {
                    b.Navigation("ConfigItem");
                });
#pragma warning restore 612, 618
        }
    }
}
